test:
  adapter: sqlite3
  encoding: unicode
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: db/maps_example_production
  pool: 5
  timeout: 5000

development:
  adapter: sqlite3
  encoding: unicode
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
